cc_library(
        name = "knapsackwithconflicts",
        hdrs = ["knapsackwithconflicts.hpp"],
        deps = [
                "//treesearchsolver:treesearchsolver",
                "@orproblems//orproblems:knapsackwithconflicts",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "knapsackwithconflicts_main",
        srcs = ["knapsackwithconflicts_main.cpp"],
        deps = [
                ":knapsackwithconflicts",
                "//treesearchsolver:read_args",
        ],
)


cc_library(
        name = "travelingsalesman",
        hdrs = ["travelingsalesman.hpp"],
        deps = [
                "//treesearchsolver:treesearchsolver",
                "@orproblems//orproblems:travelingsalesman",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "travelingsalesman_main",
        srcs = ["travelingsalesman_main.cpp"],
        deps = [
                ":travelingsalesman",
                "//treesearchsolver:read_args",
        ],
)


cc_library(
        name = "sequentialordering",
        hdrs = ["sequentialordering.hpp"],
        deps = [
                "//treesearchsolver:treesearchsolver",
                "@orproblems//orproblems:sequentialordering",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "sequentialordering_main",
        srcs = ["sequentialordering_main.cpp"],
        deps = [
                ":sequentialordering",
                "//treesearchsolver:read_args",
        ],
)


cc_library(
        name = "travelingrepairman",
        hdrs = ["travelingrepairman.hpp"],
        deps = [
                "//treesearchsolver:treesearchsolver",
                "@orproblems//orproblems:travelingrepairman",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "travelingrepairman_main",
        srcs = ["travelingrepairman_main.cpp"],
        deps = [
                ":travelingrepairman",
                "//treesearchsolver:read_args",
        ],
)


cc_library(
        name = "thieforienteering",
        hdrs = ["thieforienteering.hpp"],
        deps = [
                "//treesearchsolver:treesearchsolver",
                "@orproblems//orproblems:thieforienteering",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "thieforienteering_main",
        srcs = ["thieforienteering_main.cpp"],
        deps = [
                ":thieforienteering",
                "//treesearchsolver:read_args",
        ],
)


cc_library(
        name = "schedulingwithsdsttwt",
        hdrs = ["schedulingwithsdsttwt.hpp"],
        deps = [
                "//treesearchsolver:treesearchsolver",
                "@orproblems//orproblems:schedulingwithsdsttwt",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "schedulingwithsdsttwt_main",
        srcs = ["schedulingwithsdsttwt_main.cpp"],
        deps = [
                ":schedulingwithsdsttwt",
                "//treesearchsolver:read_args",
        ],
)


cc_library(
        name = "orderacceptanceandscheduling",
        hdrs = ["orderacceptanceandscheduling.hpp"],
        deps = [
                "//treesearchsolver:treesearchsolver",
                "@orproblems//orproblems:orderacceptanceandscheduling",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "orderacceptanceandscheduling_main",
        srcs = ["orderacceptanceandscheduling_main.cpp"],
        deps = [
                ":orderacceptanceandscheduling",
                "//treesearchsolver:read_args",
        ],
)


cc_library(
        name = "batchschedulingtotalweightedtardiness",
        hdrs = ["batchschedulingtotalweightedtardiness.hpp"],
        deps = [
                "//treesearchsolver:treesearchsolver",
                "@orproblems//orproblems:batchschedulingtotalweightedtardiness",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "batchschedulingtotalweightedtardiness_main",
        srcs = ["batchschedulingtotalweightedtardiness_main.cpp"],
        deps = [
                ":batchschedulingtotalweightedtardiness",
                "//treesearchsolver:read_args",
        ],
)


cc_library(
        name = "permutationflowshopschedulingmakespan",
        hdrs = ["permutationflowshopschedulingmakespan.hpp"],
        deps = [
                "//treesearchsolver:treesearchsolver",
                "@orproblems//orproblems:permutationflowshopschedulingmakespan",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "permutationflowshopschedulingmakespan_main",
        srcs = ["permutationflowshopschedulingmakespan_main.cpp"],
        deps = [
                ":permutationflowshopschedulingmakespan",
                "//treesearchsolver:read_args",
        ],
)


cc_library(
        name = "permutationflowshopschedulingtct",
        hdrs = ["permutationflowshopschedulingtct.hpp"],
        deps = [
                "//treesearchsolver:treesearchsolver",
                "@orproblems//orproblems:permutationflowshopschedulingtct",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "permutationflowshopschedulingtct_main",
        srcs = ["permutationflowshopschedulingtct_main.cpp"],
        deps = [
                ":permutationflowshopschedulingtct",
                "//treesearchsolver:read_args",
        ],
)


cc_library(
        name = "permutationflowshopschedulingtt",
        hdrs = ["permutationflowshopschedulingtt.hpp"],
        deps = [
                "//treesearchsolver:treesearchsolver",
                "@orproblems//orproblems:permutationflowshopschedulingtt",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "permutationflowshopschedulingtt_main",
        srcs = ["permutationflowshopschedulingtt_main.cpp"],
        deps = [
                ":permutationflowshopschedulingtt",
                "//treesearchsolver:read_args",
        ],
)


cc_library(
        name = "nowaitjobshopschedulingmakespan",
        hdrs = ["nowaitjobshopschedulingmakespan.hpp"],
        deps = [
                "//treesearchsolver:treesearchsolver",
                "@orproblems//orproblems:nowaitjobshopschedulingmakespan",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "nowaitjobshopschedulingmakespan_main",
        srcs = ["nowaitjobshopschedulingmakespan_main.cpp"],
        deps = [
                ":nowaitjobshopschedulingmakespan",
                "//treesearchsolver:read_args",
        ],
        copts = ["-std=c++14"],
        linkopts = ["-std=c++14"],
)


cc_library(
        name = "simpleassemblylinebalancing1",
        hdrs = ["simpleassemblylinebalancing1.hpp"],
        deps = [
                "//treesearchsolver:treesearchsolver",
                "@orproblems//orproblems:simpleassemblylinebalancing1",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "simpleassemblylinebalancing1_main",
        srcs = ["simpleassemblylinebalancing1_main.cpp"],
        deps = [
                ":simpleassemblylinebalancing1",
                "//treesearchsolver:read_args",
        ],
)


cc_library(
        name = "ushapedassemblylinebalancing1",
        hdrs = ["ushapedassemblylinebalancing1.hpp"],
        deps = [
                "//treesearchsolver:treesearchsolver",
                "@orproblems//orproblems:ushapedassemblylinebalancing1",
        ],
        visibility = ["//visibility:public"],
)

cc_binary(
        name = "ushapedassemblylinebalancing1_main",
        srcs = ["ushapedassemblylinebalancing1_main.cpp"],
        deps = [
                ":ushapedassemblylinebalancing1",
                "//treesearchsolver:read_args",
        ],
)


